### ISSUE TITLE
 Some improvements under high baud rate of serial port

### ISSUE THREAD

**Issue by Linjieqiang** [MaJerle/STM32_USART_DMA_RX#36]
Hello, @MaJerle . 

My current serial port application is 5Mbps, using RTOS thread processing. I turned on the DMA HT and FT interrupts by referring to your tutorial, and the serial port interrupt line, but my maximum data per packet is 64 words. section, in this case, should I turn off the DMA HT interrupt to reduce system overhead?

**Comment by MaJerle** [comment]
No. To reduce the  to DMAinterrupt frequency, increase the buffer that is assigned to DMA.

**Comment by MaJerle** [comment]
Please read the full readme article why all these interrupts are needed. You could remove TC and HT interrupts, but inly if you can prove in the application that whoever sends you the data will never send more than your buffer size, and will ensure at least for one byte of data line to be idle, for idle interrupts.

I have been running UART at 10Mbit successfully with all three interrupts. There is practically no overhead.
